# Generated by Django 5.2.3 on 2025-12-03 06:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_patientprofile_patient_id_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='history_id',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='pairing_code',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='working_days',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='working_hours_end',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='working_hours_start',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='original_therapist_patient',
            field=models.ForeignKey(blank=True, help_text='Reference to the original patient profile created by therapist (if merged)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_accounts', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='buffer_between_sessions',
            field=models.IntegerField(default=15, help_text='Buffer time between sessions in minutes'),
        ),
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('merged', 'Merged with Existing Patient'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message from patient', null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry date for the request', null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('merged_with_patient', models.ForeignKey(blank=True, help_text='The therapist-created patient profile this was merged with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_requests', to='users.patientprofile')),
                ('patient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests', to='users.therapistprofile')),
            ],
            options={
                'db_table': 'connection_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['therapist', 'status'], name='therapist_status_idx'), models.Index(fields=['patient_user', 'status'], name='patient_status_idx'), models.Index(fields=['expires_at'], name='expires_at_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('patient_user', 'therapist'), name='unique_pending_request')],
            },
        ),
    ]
