# Generated by Django 5.2.3 on 2026-04-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_therapistprofile_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistprofile',
            name='is_public',
            field=models.BooleanField(blank=True, db_index=True, default=None, help_text='When True, this therapist appears in the public therapist directory.', null=True),
        ),
    ]
