"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta # Import timedelta for JWT settings
import os # Import os for environment variables
from dotenv import load_dotenv # Import load_dotenv for .env file support
import dj_database_url # Import dj_database_url for DATABASE_URL support
from celery.schedules import crontab

# Load environment variables from .env file (if it exists)
# Make sure your .env file is in the same directory as manage.py
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# IMPORTANT: In production, this should be loaded from an environment variable!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-xlb)p+*0f81&n^mnnta1_-n%mw^dwt#6tgqrcp#5b7+hpp(v^g")

# SECURITY WARNING: don't run with debug turned on in production!
# IMPORTANT: In production, set DEBUG to False!
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() == "true"

# ALLOWED_HOSTS for production. Add your domain and Elastic Beanstalk URL here.
# For development, if DEBUG is True, ['*'] is often used, but it's safer to specify.
# ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if os.environ.get("DJANGO_ALLOWED_HOSTS") else []
ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Third-party apps
    "channels",
    "rest_framework",                 # Django REST Framework
    "corsheaders",                    # For handling Cross-Origin Resource Sharing
    "rest_framework_simplejwt",       # For JSON Web Token authentication
    "rest_framework_simplejwt.token_blacklist",  # JWT token blacklist
    "drf_spectacular",                # For OpenAPI (Swagger UI) documentation
    "storages",                       # For AWS S3 integration (if using)

    # Your custom apps
    "authenticator",           # Your custom authentication app (contains CustomUser)
    "users",          # User profiles (if separated from auth.CustomUser)
    "therapy_sessions",       # Therapy session management
    "history",        # User history/logs
    "core",
    "patients",       # Patient wellness features (mood, journal, relaxation, goals)
    # Removed: "transcription" and "soap" - migrated to FastAPI AI service
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware", # CORS middleware must be high up
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug", # Added for debug purposes
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"
ASGI_APPLICATION = "app.asgi.application"

# Channels layer configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# PostgreSQL Database Configuration
# Uses DATABASE_URL from .env for production and development
DATABASES = {
    'default': dj_database_url.config(default=os.environ.get('DATABASE_URL'))
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Karachi"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # For collecting static files in production
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Media files (User-uploaded content like profile pictures, audio)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --- Custom Settings for MindScribe Project ---

# Custom User Model
# This tells Django to use your CustomUser model from the 'auth' app
AUTH_USER_MODEL = 'users.User'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication', # Optional, for browsable API
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated', # Default to requiring authentication
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', # For OpenAPI
}

# Django REST Framework Simple JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.environ.get("JWT_ACCESS_TOKEN_LIFETIME", "60"))),
    'REFRESH_TOKEN_LIFETIME': timedelta(minutes=int(os.environ.get("JWT_REFRESH_TOKEN_LIFETIME", "10080"))),
    'ROTATE_REFRESH_TOKENS': os.environ.get("JWT_ROTATE_REFRESH_TOKENS", "True").lower() == "true",
    'BLACKLIST_AFTER_ROTATION': os.environ.get("JWT_BLACKLIST_AFTER_ROTATION", "True").lower() == "true",
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=int(os.environ.get("JWT_ACCESS_TOKEN_LIFETIME", "60"))),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(minutes=int(os.environ.get("JWT_REFRESH_TOKEN_LIFETIME", "10080"))),
}

# CORS Headers settings
# IMPORTANT: In production, restrict CORS_ALLOWED_ORIGINS to your actual frontend domain(s)!
# CORS_ALLOWED_ORIGINS = [
#     os.environ.get("FRONTEND_URL", "http://localhost:3000"),  # Read from environment variable
#     # Add other local development origins if needed (e.g., for web testing)
# ]


# Enable this setting to allow requests from all origins
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True # Allow cookies/auth headers to be sent cross-origin

# CSRF Trusted Origins for Railway and Localhood
CSRF_TRUSTED_ORIGINS = [
    "https://*.railway.app",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# DRF Spectacular (OpenAPI/Swagger) settings
SPECTACULAR_SETTINGS = {
    'TITLE': os.environ.get("SITE_NAME", "MindScribe") + ' API',
    'DESCRIPTION': 'API documentation for the MindScribe project backend.',
    'VERSION': os.environ.get("VERSION", "1.0.0"),
    'SERVE_INCLUDE_SCHEMA': DEBUG, # Only serve schema (Swagger UI) in DEBUG mode
    # Other settings like security schemes, contact info, etc.
    'SCHEMA_PATH_PREFIX': r'/api/v[0-9]', # Example: only include paths starting with /api/vX
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'displayRequestDuration': True,
        'filter': True,
        'showExtensions': True,
        'showCommonExtensions': True,
    },
    'COMPONENT_SPLIT_REQUEST': True, # Improves performance for large schemas
    'ENUM_NAME_OVERRIDES': {
        'SessionStatusEnum': 'therapy_sessions.models.Session.SESSION_STATUS',
        'SessionTypeEnum': 'therapy_sessions.models.Session.SESSION_TYPES',
        'MoodRatingEnum': 'therapy_sessions.models.Session.MOOD_RATINGS',
    },
}

# Celery settings (for background tasks like reminders, retries, AI pipeline)
# IMPORTANT: Use environment variables for production.
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', os.environ.get('REDIS_URL', 'redis://localhost:6379/0'))
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', os.environ.get('REDIS_URL', 'redis://localhost:6379/0'))
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = USE_TZ

# Reminder matching windows
DAILY_REMINDER_WINDOW_MINUTES = int(os.environ.get('DAILY_REMINDER_WINDOW_MINUTES', '5'))
SESSION_REMINDER_WINDOW_MINUTES = int(os.environ.get('SESSION_REMINDER_WINDOW_MINUTES', '10'))

# Push retry/dead-letter controls
PUSH_RETRY_MAX_TO_PROCESS = int(os.environ.get('PUSH_RETRY_MAX_TO_PROCESS', '200'))
PUSH_DEAD_LETTER_AFTER_HOURS = int(os.environ.get('PUSH_DEAD_LETTER_AFTER_HOURS', '24'))

# Celery Beat periodic tasks for reminders and delivery retries
CELERY_BEAT_SCHEDULE = {
    'send-session-reminders-every-minute': {
        'task': 'patients.tasks.send_session_reminder_notifications_task',
        'schedule': crontab(),
    },
    'send-mood-reminders-every-minute': {
        'task': 'patients.tasks.send_mood_reminder_notifications_task',
        'schedule': crontab(),
    },
    'send-journal-reminders-every-minute': {
        'task': 'patients.tasks.send_journal_reminder_notifications_task',
        'schedule': crontab(),
    },
    'retry-failed-push-every-5-minutes': {
        'task': 'patients.tasks.retry_failed_push_notifications_task',
        'schedule': crontab(minute='*/5'),
        'kwargs': {
            'max_to_process': PUSH_RETRY_MAX_TO_PROCESS,
            'dead_letter_after_hours': PUSH_DEAD_LETTER_AFTER_HOURS,
        },
    },
    'retry-failed-websocket-every-minute': {
        'task': 'patients.tasks.retry_failed_websocket_notifications_task',
        'schedule': crontab(),
    },
}

# AWS S3 Storage settings (using django-storages and boto3)
# Only enable these if you are ready to use S3 for file storage
# If you're developing locally and not using S3 yet, you can comment this out
# or ensure DEFAULT_FILE_STORAGE is not set to S3Boto3Storage.
# AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
# AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
# AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
# AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1') # e.g., 'ap-south-1' for Mumbai
# AWS_S3_FILE_OVERWRITE = False # Don't overwrite files with the same name
# AWS_DEFAULT_ACL = None # Or 'public-read' if files should be publicly accessible
# AWS_S3_VERIFY_SSL = True
# AWS_QUERYSTRING_AUTH = False # Don't include auth in URL for public files
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com' # Optional: if using a custom domain

# --- Authentication and Session Settings ---

# Authentication settings
MAX_LOGIN_ATTEMPTS = int(os.environ.get("MAX_LOGIN_ATTEMPTS", "5"))
LOCKOUT_DURATION = int(os.environ.get("LOCKOUT_DURATION", "900"))  # 15 minutes
RATE_LIMIT_REQUESTS = int(os.environ.get("RATE_LIMIT_REQUESTS", "100"))
RATE_LIMIT_WINDOW = int(os.environ.get("RATE_LIMIT_WINDOW", "900"))  # 15 minutes
SESSION_TIMEOUT = int(os.environ.get("SESSION_TIMEOUT", "3600"))  # 1 hour

# Session settings
SESSION_COOKIE_AGE = SESSION_TIMEOUT
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# --- Security Settings ---
SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "False").lower() == "true"
SESSION_COOKIE_SECURE = os.environ.get("SESSION_COOKIE_SECURE", "False").lower() == "true"
CSRF_COOKIE_SECURE = os.environ.get("CSRF_COOKIE_SECURE", "False").lower() == "true"

# --- Email Configuration ---
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "").strip()
_email_from_env = os.environ.get("EMAIL_FROM", "").strip()
EMAIL_FROM = _email_from_env or "info@mindscribe.live"
_default_from_env = os.environ.get("DEFAULT_FROM_EMAIL", "").strip()
DEFAULT_FROM_EMAIL = _default_from_env or EMAIL_FROM

# --- Frontend Configuration ---
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:5173")

# --- Site Configuration ---
SITE_NAME = os.environ.get("SITE_NAME", "MindScribe")
VERSION = os.environ.get("VERSION", "1.0.0")

# --- Media Files Configuration ---
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# --- AI Services Configuration ---
BACKEND_URL = os.environ.get("BACKEND_URL", "http://localhost:8000")
AI_SERVICE_URL = os.environ.get("AI_SERVICE_URL", "http://localhost:8001")
AI_SERVICE_SECRET_KEY = os.environ.get("AI_SERVICE_SECRET_KEY", SECRET_KEY)
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
