# Generated by Django 5.2.3 on 2025-08-19 12:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapy_sessions', '0007_alter_session_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('relative_seconds', models.FloatField(blank=True, help_text='Seconds from session start when captured', null=True)),
                ('mood_label', models.CharField(help_text='Primary mood label e.g. anxious, calm', max_length=50)),
                ('mood_score', models.FloatField(blank=True, help_text='0-1 normalized mood intensity or positivity', null=True)),
                ('valence', models.FloatField(blank=True, help_text='-1 negative to +1 positive', null=True)),
                ('arousal', models.FloatField(blank=True, help_text='0 calm to 1 excited', null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='ai', max_length=30)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_snapshots', to='therapy_sessions.session')),
            ],
            options={
                'db_table': 'mood_snapshots',
                'ordering': ['captured_at'],
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('language_detected', models.CharField(blank=True, max_length=10, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='therapy_sessions.session')),
            ],
            options={
                'db_table': 'transcriptions',
            },
        ),
        migrations.CreateModel(
            name='RealtimeTranscriptionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('initializing', 'Initializing'), ('active', 'Active'), ('closing', 'Closing'), ('closed', 'Closed'), ('error', 'Error')], default='initializing', max_length=20)),
                ('openai_connection_id', models.CharField(blank=True, max_length=100, null=True)),
                ('websocket_url', models.CharField(blank=True, help_text='URL the client can connect to (ephemeral or proxied)', max_length=500, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_transcription', to='therapy_sessions.session')),
                ('transcription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtime_session', to='transcription.transcription')),
            ],
            options={
                'db_table': 'realtime_transcription_sessions',
            },
        ),
        migrations.CreateModel(
            name='TranscriptionSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_type', models.CharField(choices=[('patient', 'Patient'), ('therapist', 'Therapist'), ('unknown', 'Unknown')], max_length=20)),
                ('speaker_id', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.TextField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='transcription.transcription')),
            ],
            options={
                'db_table': 'transcription_segments',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='EmotionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_emotion', models.CharField(max_length=50)),
                ('emotion_scores', models.JSONField(default=dict)),
                ('valence', models.FloatField()),
                ('arousal', models.FloatField()),
                ('confidence', models.FloatField()),
                ('segment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emotion', to='transcription.transcriptionsegment')),
            ],
            options={
                'db_table': 'emotion_analysis',
            },
        ),
    ]
