"""SOAP note generation & management endpoints."""
from rest_framework import views, permissions, status, serializers
from rest_framework.response import Response
from django.shortcuts import get_object_or_404
from django.db import transaction
from django.utils import timezone
from typing import List
import os
import logging
import json

from .models import SOAPNote, SOAPNoteVersion
from drf_spectacular.utils import extend_schema, OpenApiExample, OpenApiResponse
from therapy_sessions.models import Session

logger = logging.getLogger(__name__)

try:
	import requests
except ImportError:  # pragma: no cover
	requests = None  # type: ignore

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
SOAP_MODEL = os.getenv("OPENAI_SOAP_MODEL", "gpt-4o-mini")


class BatchSOAPRequestSerializer(serializers.Serializer):
	session_ids = serializers.ListField(
		child=serializers.UUIDField(),
		help_text='List of session UUIDs to generate/update SOAP notes for'
	)


class BatchSOAPResponseSerializer(serializers.Serializer):
	detail = serializers.CharField()
	results = serializers.DictField(child=serializers.CharField())


class SOAPNoteSerializer(serializers.Serializer):
	id = serializers.UUIDField()
	patient = serializers.UUIDField()
	therapist = serializers.UUIDField()
	sessions = serializers.ListField(child=serializers.UUIDField())
	subjective = serializers.CharField(allow_null=True)
	objective = serializers.CharField(allow_null=True)
	assessment = serializers.CharField(allow_null=True)
	plan = serializers.CharField(allow_null=True)
	status = serializers.CharField()
	created_at = serializers.DateTimeField()
	updated_at = serializers.DateTimeField()


class BatchSOAPGenerationView(views.APIView):
	permission_classes = [permissions.IsAuthenticated]

	@extend_schema(
		tags=['SOAP'],
		summary='Batch generate or update SOAP notes',
		description='Generates or updates SOAP notes for the provided session IDs using existing transcripts.',
		request=BatchSOAPRequestSerializer,
		responses={200: BatchSOAPResponseSerializer},
		examples=[
			OpenApiExample(
				'Batch Request',
				value={'session_ids': ['123e4567-e89b-12d3-a456-426614174000', '223e4567-e89b-12d3-a456-426614174000']}
			),
			OpenApiExample(
				'Batch Response',
				value={'detail': 'batch processed', 'results': {'123e...4000': 'ok', '223e...4000': 'skipped:no patient'}}
			)
		]
	)
	def post(self, request):
		serializer = BatchSOAPRequestSerializer(data=request.data)
		serializer.is_valid(raise_exception=True)
		session_ids: List[str] = serializer.validated_data['session_ids']
		results = {}
		for sid in session_ids:
			try:
				session = Session.objects.get(id=sid)
				if session.patient is None:
					results[str(sid)] = 'skipped:no patient'
					continue
				note = self._generate_or_update_soap(session)
				results[str(sid)] = 'ok' if note else 'skipped'
			except Exception as e:  # pragma: no cover
				logger.exception("SOAP batch error for %s", sid)
				results[str(sid)] = f'error:{e}'
		return Response({'detail': 'batch processed', 'results': results})

	def _generate_or_update_soap(self, session: Session) -> SOAPNote | None:
		# Gather transcript text (if exists)
		try:
			transcription = session.transcription
			segments = transcription.segments.order_by('start_time')
			joined_text = "\n".join(s.text for s in segments)
		except Exception:
			joined_text = ''
		if not joined_text.strip():
			return None
		if not OPENAI_API_KEY or not requests:
			logger.warning('SOAP generation skipped: missing API key or requests')
			return None
		prompt = (
			"Create a structured SOAP note (JSON) summarizing these therapy session transcripts. "
			"Keys: subjective, objective, assessment, plan. Keep each concise.\n" + joined_text[:6000]
		)
		resp = requests.post(
			'https://api.openai.com/v1/chat/completions',
			headers={'Authorization': f'Bearer {OPENAI_API_KEY}', 'Content-Type': 'application/json'},
			json={
				'model': SOAP_MODEL,
				'messages': [
					{'role': 'system', 'content': 'Return ONLY valid JSON.'},
					{'role': 'user', 'content': prompt},
				],
				'temperature': 0.4,
			},
			timeout=40,
		)
		if resp.status_code >= 300:
			logger.error('SOAP generation failed %s %s', resp.status_code, resp.text)
			return None
		content = resp.json()['choices'][0]['message']['content']
		try:
			parsed = json.loads(content)
		except Exception:
			parsed = {}
		note, created = SOAPNote.objects.get_or_create(
			therapist=session.therapist,
			patient=session.patient,
			status='draft'
		)
		# Link session
		note.sessions.add(session)
		# Versioning
		with transaction.atomic():
			version_number = note.versions.count() + 1
			SOAPNoteVersion.objects.create(
				soap_note=note,
				version_number=version_number,
				subjective=parsed.get('subjective'),
				objective=parsed.get('objective'),
				assessment=parsed.get('assessment'),
				plan=parsed.get('plan'),
				created_by=session.therapist,
				change_summary='Autogenerated from transcript',
			)
			# Update current fields
			note.subjective = parsed.get('subjective')
			note.objective = parsed.get('objective')
			note.assessment = parsed.get('assessment')
			note.plan = parsed.get('plan')
			note.updated_at = timezone.now()
			note.save()
		return note


class SOAPNoteDetailView(views.APIView):
	permission_classes = [permissions.IsAuthenticated]

	@extend_schema(
		tags=['SOAP'],
		summary='Retrieve a SOAP note',
		responses={200: SOAPNoteSerializer},
		examples=[
			OpenApiExample(
				'SOAP Note',
				value={
					'id': '323e4567-e89b-12d3-a456-426614174000',
					'patient': '123e4567-e89b-12d3-a456-426614174000',
					'therapist': '223e4567-e89b-12d3-a456-426614174000',
					'sessions': ['423e4567-e89b-12d3-a456-426614174000'],
					'subjective': 'Patient reports reduced anxiety.',
					'objective': 'Calmer affect, normal speech.',
					'assessment': 'Generalized anxiety improving.',
					'plan': 'Continue CBT and breathing exercises.',
					'status': 'draft',
					'created_at': '2025-08-19T10:00:00Z',
					'updated_at': '2025-08-19T10:05:00Z'
				}
			)
		]
	)
	def get(self, request, note_id: str):
		note = get_object_or_404(SOAPNote, id=note_id)
		if request.user not in [note.therapist, note.patient]:
			return Response({'detail': 'Forbidden'}, status=403)
		return Response({
			'id': str(note.id),
			'patient': note.patient_id,
			'therapist': note.therapist_id,
			'sessions': [str(s.id) for s in note.sessions.all()],
			'subjective': note.subjective,
			'objective': note.objective,
			'assessment': note.assessment,
			'plan': note.plan,
			'status': note.status,
			'created_at': note.created_at,
			'updated_at': note.updated_at,
		})
