"""SOAP note generation & management endpoints."""
from rest_framework import views, permissions, status
from rest_framework.response import Response
from django.shortcuts import get_object_or_404
from django.db import transaction
from django.utils import timezone
from typing import List
import os
import logging
import json

from .models import SOAPNote, SOAPNoteVersion
from therapy_sessions.models import Session

logger = logging.getLogger(__name__)

try:
	import requests
except ImportError:  # pragma: no cover
	requests = None  # type: ignore

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
SOAP_MODEL = os.getenv("OPENAI_SOAP_MODEL", "gpt-4o-mini")


class BatchSOAPGenerationView(views.APIView):
	permission_classes = [permissions.IsAuthenticated]

	def post(self, request):
		session_ids: List[str] = request.data.get('session_ids', [])
		if not isinstance(session_ids, list) or not session_ids:
			return Response({'detail': 'session_ids list required'}, status=400)
		results = {}
		for sid in session_ids:
			try:
				session = Session.objects.get(id=sid)
				if session.patient is None:
					results[sid] = 'skipped:no patient'
					continue
				note = self._generate_or_update_soap(session)
				results[sid] = 'ok' if note else 'skipped'
			except Exception as e:  # pragma: no cover
				logger.exception("SOAP batch error for %s", sid)
				results[sid] = f'error:{e}'
		return Response({'detail': 'batch processed', 'results': results})

	def _generate_or_update_soap(self, session: Session) -> SOAPNote | None:
		# Gather transcript text (if exists)
		try:
			transcription = session.transcription
			segments = transcription.segments.order_by('start_time')
			joined_text = "\n".join(s.text for s in segments)
		except Exception:
			joined_text = ''
		if not joined_text.strip():
			return None
		if not OPENAI_API_KEY or not requests:
			logger.warning('SOAP generation skipped: missing API key or requests')
			return None
		prompt = (
			"Create a structured SOAP note (JSON) summarizing these therapy session transcripts. "
			"Keys: subjective, objective, assessment, plan. Keep each concise.\n" + joined_text[:6000]
		)
		resp = requests.post(
			'https://api.openai.com/v1/chat/completions',
			headers={'Authorization': f'Bearer {OPENAI_API_KEY}', 'Content-Type': 'application/json'},
			json={
				'model': SOAP_MODEL,
				'messages': [
					{'role': 'system', 'content': 'Return ONLY valid JSON.'},
					{'role': 'user', 'content': prompt},
				],
				'temperature': 0.4,
			},
			timeout=40,
		)
		if resp.status_code >= 300:
			logger.error('SOAP generation failed %s %s', resp.status_code, resp.text)
			return None
		content = resp.json()['choices'][0]['message']['content']
		try:
			parsed = json.loads(content)
		except Exception:
			parsed = {}
		note, created = SOAPNote.objects.get_or_create(
			therapist=session.therapist,
			patient=session.patient,
			status='draft'
		)
		# Link session
		note.sessions.add(session)
		# Versioning
		with transaction.atomic():
			version_number = note.versions.count() + 1
			SOAPNoteVersion.objects.create(
				soap_note=note,
				version_number=version_number,
				subjective=parsed.get('subjective'),
				objective=parsed.get('objective'),
				assessment=parsed.get('assessment'),
				plan=parsed.get('plan'),
				created_by=session.therapist,
				change_summary='Autogenerated from transcript',
			)
			# Update current fields
			note.subjective = parsed.get('subjective')
			note.objective = parsed.get('objective')
			note.assessment = parsed.get('assessment')
			note.plan = parsed.get('plan')
			note.updated_at = timezone.now()
			note.save()
		return note


class SOAPNoteDetailView(views.APIView):
	permission_classes = [permissions.IsAuthenticated]

	def get(self, request, note_id: str):
		note = get_object_or_404(SOAPNote, id=note_id)
		if request.user not in [note.therapist, note.patient]:
			return Response({'detail': 'Forbidden'}, status=403)
		return Response({
			'id': str(note.id),
			'patient': note.patient_id,
			'therapist': note.therapist_id,
			'sessions': [str(s.id) for s in note.sessions.all()],
			'subjective': note.subjective,
			'objective': note.objective,
			'assessment': note.assessment,
			'plan': note.plan,
			'status': note.status,
			'created_at': note.created_at,
			'updated_at': note.updated_at,
		})
