# Generated by Django 5.2.3 on 2025-08-06 18:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('exercise', 'Exercise/Physical Activity'), ('meditation', 'Meditation/Mindfulness'), ('social', 'Social Activity'), ('work', 'Work/Study'), ('hobby', 'Hobby/Creative Activity'), ('therapy', 'Therapy Session'), ('medication', 'Medication'), ('sleep', 'Sleep'), ('meal', 'Meal/Nutrition'), ('self_care', 'Self Care'), ('outdoor', 'Outdoor Activity'), ('entertainment', 'Entertainment/Leisure'), ('other', 'Other')], max_length=20)),
                ('activity_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('intensity', models.IntegerField(blank=True, help_text='Activity intensity (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('mood_before', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('mood_after', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('energy_before', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('energy_after', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('with_others', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('activity_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='CopingStrategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strategy_type', models.CharField(choices=[('breathing', 'Breathing Exercises'), ('meditation', 'Meditation'), ('physical', 'Physical Exercise'), ('social', 'Social Support'), ('creative', 'Creative Activities'), ('cognitive', 'Cognitive Techniques'), ('distraction', 'Distraction Techniques'), ('relaxation', 'Relaxation Techniques'), ('grounding', 'Grounding Techniques'), ('journaling', 'Journaling'), ('music', 'Music/Audio'), ('nature', 'Nature/Outdoors'), ('other', 'Other')], max_length=20)),
                ('strategy_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('times_used', models.IntegerField(default=0)),
                ('average_effectiveness', models.FloatField(default=0.0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('best_situations', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('learned_from_therapist', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coping_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coping_strategies',
                'ordering': ['-average_effectiveness', '-times_used'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('entry_type', models.CharField(choices=[('daily', 'Daily Journal'), ('gratitude', 'Gratitude Entry'), ('reflection', 'Self Reflection'), ('dream', 'Dream Journal'), ('therapy', 'Post-Therapy Reflection'), ('milestone', 'Milestone/Achievement'), ('challenge', 'Challenge/Difficulty'), ('free_form', 'Free Form')], default='free_form', max_length=20)),
                ('privacy_level', models.CharField(choices=[('private', 'Private (Only Me)'), ('therapist', 'Share with Therapist'), ('anonymous', 'Anonymous Sharing')], default='private', max_length=20)),
                ('mood_before', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('mood_after', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, null=True)),
                ('word_count', models.IntegerField(default=0)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journal_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mood', models.CharField(choices=[('very_sad', 'Very Sad'), ('sad', 'Sad'), ('neutral', 'Neutral'), ('happy', 'Happy'), ('very_happy', 'Very Happy')], max_length=20)),
                ('mood_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('energy_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('sleep_quality', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('anxiety_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('stress_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('triggers', models.CharField(blank=True, help_text='Comma-separated list of triggers', max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('weather', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('coping_strategies_used', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mood_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_goals',
            },
        ),
        migrations.CreateModel(
            name='PatientMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('milestone_type', models.CharField(choices=[('therapy', 'Therapy Milestone'), ('personal', 'Personal Achievement'), ('health', 'Health Improvement'), ('social', 'Social Progress'), ('work', 'Work/Career'), ('education', 'Educational'), ('relationship', 'Relationship'), ('habit', 'Habit Formation'), ('goal', 'Goal Achievement'), ('other', 'Other')], max_length=20)),
                ('importance_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('mood_impact', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('celebration_notes', models.TextField(blank=True, null=True)),
                ('achieved_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to=settings.AUTH_USER_MODEL)),
                ('related_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.patientgoal')),
            ],
            options={
                'db_table': 'patient_milestones',
                'ordering': ['-achieved_date'],
            },
        ),
        migrations.CreateModel(
            name='ReflectionPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_text', models.TextField()),
                ('prompt_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('session_based', 'Session Based'), ('custom', 'Custom')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reflection_prompts',
            },
        ),
        migrations.CreateModel(
            name='ReflectionEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_entries', to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='history.reflectionprompt')),
            ],
            options={
                'db_table': 'reflection_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SymptomTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptom_type', models.CharField(choices=[('anxiety', 'Anxiety'), ('depression', 'Depression'), ('panic', 'Panic Attacks'), ('mood_swings', 'Mood Swings'), ('irritability', 'Irritability'), ('fatigue', 'Fatigue'), ('concentration', 'Concentration Issues'), ('sleep_issues', 'Sleep Issues'), ('appetite', 'Appetite Changes'), ('social_withdrawal', 'Social Withdrawal'), ('physical_pain', 'Physical Pain'), ('headaches', 'Headaches'), ('nausea', 'Nausea'), ('other', 'Other')], max_length=20)),
                ('symptom_name', models.CharField(blank=True, max_length=200, null=True)),
                ('severity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('triggers', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('coping_strategies', models.TextField(blank=True, null=True)),
                ('relief_methods', models.TextField(blank=True, null=True)),
                ('effectiveness_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('symptom_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'symptom_tracker',
                'ordering': ['-symptom_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('prescribed_time', models.TimeField()),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('was_taken', models.BooleanField(default=False)),
                ('missed_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('mood_before', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('mood_after', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('effectiveness_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('log_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medication_logs',
                'ordering': ['-log_date', '-prescribed_time'],
                'unique_together': {('patient', 'medication_name', 'log_date', 'prescribed_time')},
            },
        ),
        migrations.CreateModel(
            name='ProgressTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('overall_wellbeing', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('symptom_severity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('functional_improvement', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('medication_adherence', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'progress_tracking',
                'unique_together': {('patient', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sleep_date', models.DateField()),
                ('bedtime', models.TimeField(blank=True, null=True)),
                ('sleep_time', models.TimeField(blank=True, null=True)),
                ('wake_time', models.TimeField(blank=True, null=True)),
                ('hours_slept', models.FloatField(blank=True, null=True)),
                ('times_woken', models.IntegerField(default=0)),
                ('sleep_quality', models.CharField(blank=True, choices=[('very_poor', 'Very Poor'), ('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=20, null=True)),
                ('sleep_quality_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('pre_sleep_activities', models.TextField(blank=True, null=True)),
                ('sleep_environment', models.CharField(blank=True, max_length=200, null=True)),
                ('dreams_remembered', models.BooleanField(default=False)),
                ('dream_content', models.TextField(blank=True, null=True)),
                ('morning_mood', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('morning_energy', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sleep_logs',
                'ordering': ['-sleep_date'],
                'unique_together': {('patient', 'sleep_date')},
            },
        ),
    ]
