# Generated by Django 5.2.3 on 2026-02-06 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='mood_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
