# Generated by Django 5.2.3 on 2025-12-03 06:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0007_alter_session_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistDateOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Specific date for override')),
                ('end_date', models.DateField(blank=True, help_text='End date for multi-day override (vacation)', null=True)),
                ('override_type', models.CharField(choices=[('day_off', 'Day Off'), ('vacation', 'Vacation'), ('holiday', 'Holiday'), ('special_hours', 'Special Hours'), ('extra_availability', 'Extra Availability')], default='day_off', max_length=20)),
                ('is_available', models.BooleanField(default=False, help_text='Is therapist available on this date?')),
                ('start_time', models.TimeField(blank=True, help_text='Start time if available', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time if available', null=True)),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for the override', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'therapist_date_overrides',
                'ordering': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='therapistavailability',
            options={'ordering': ['day_of_week', 'start_time']},
        ),
        migrations.RemoveConstraint(
            model_name='session',
            name='patient_or_quick_name',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='quick_session_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='transcription_idx',
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='therapistavailability',
            unique_together={('therapist', 'day_of_week', 'effective_from')},
        ),
        migrations.AddField(
            model_name='session',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='emergency_reason',
            field=models.TextField(blank=True, help_text='Reason for emergency request', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='is_emergency',
            field=models.BooleanField(default=False, help_text='Is this an emergency session request'),
        ),
        migrations.AddField(
            model_name='session',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Is this part of a recurring series'),
        ),
        migrations.AddField(
            model_name='session',
            name='recurrence_index',
            field=models.PositiveIntegerField(blank=True, help_text='Index in the recurring series (1, 2, 3...)', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='recurrence_parent',
            field=models.ForeignKey(blank=True, help_text='Parent session if this is a recurring instance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_instances', to='therapy_sessions.session'),
        ),
        migrations.AddField(
            model_name='session',
            name='recurring_weeks',
            field=models.PositiveIntegerField(blank=True, help_text='Number of weeks for recurring sessions', null=True),
        ),
        migrations.AddField(
            model_name='therapistavailability',
            name='break_end',
            field=models.TimeField(blank=True, help_text='End of break period', null=True),
        ),
        migrations.AddField(
            model_name='therapistavailability',
            name='break_start',
            field=models.TimeField(blank=True, help_text='Start of break period', null=True),
        ),
        migrations.AddField(
            model_name='therapistavailability',
            name='buffer_minutes',
            field=models.IntegerField(default=15, help_text='Buffer time between sessions in minutes'),
        ),
        migrations.AddField(
            model_name='therapistavailability',
            name='default_session_duration',
            field=models.IntegerField(default=60, help_text='Default session duration in minutes for this day'),
        ),
        migrations.AddField(
            model_name='therapistavailability',
            name='is_day_off',
            field=models.BooleanField(default=False, help_text='Mark this day as completely unavailable'),
        ),
        migrations.AddField(
            model_name='therapistavailability',
            name='is_in_person_available',
            field=models.BooleanField(default=True, help_text='Can do in-person sessions on this day'),
        ),
        migrations.AddField(
            model_name='therapistavailability',
            name='max_sessions_per_day',
            field=models.IntegerField(default=8, help_text='Maximum sessions allowed on this day'),
        ),
        migrations.AlterField(
            model_name='session',
            name='patient',
            field=models.ForeignKey(default=0, help_text='Patient for this session', on_delete=django.db.models.deletion.CASCADE, related_name='patient_sessions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group'), ('family', 'Family'), ('couples', 'Couples'), ('assessment', 'Assessment'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('EMERGENCY_REQUESTED', 'Emergency Requested'), ('UPCOMING', 'Upcoming'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled'), ('NO_SHOW', 'No Show'), ('NEEDS_RESCHEDULING', 'Needs Rescheduling')], default='UPCOMING', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessiontemplate',
            name='session_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group'), ('family', 'Family'), ('couples', 'Couples'), ('assessment', 'Assessment'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='therapistavailability',
            name='effective_from',
            field=models.DateField(blank=True, help_text='Start date for this availability (null = always)', null=True),
        ),
        migrations.AlterField(
            model_name='therapistavailability',
            name='effective_until',
            field=models.DateField(blank=True, help_text='End date for this availability (null = indefinite)', null=True),
        ),
        migrations.AlterField(
            model_name='therapistavailability',
            name='end_time',
            field=models.TimeField(help_text='End of working hours for this day'),
        ),
        migrations.AlterField(
            model_name='therapistavailability',
            name='is_online_available',
            field=models.BooleanField(default=True, help_text='Can do online sessions on this day'),
        ),
        migrations.AlterField(
            model_name='therapistavailability',
            name='location',
            field=models.CharField(blank=True, help_text='Default location for this day', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='therapistavailability',
            name='start_time',
            field=models.TimeField(help_text='Start of working hours for this day'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['is_recurring', 'recurrence_parent'], name='recurring_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['is_emergency'], name='emergency_idx'),
        ),
        migrations.AddIndex(
            model_name='therapistavailability',
            index=models.Index(fields=['therapist', 'day_of_week'], name='avail_therapist_day_idx'),
        ),
        migrations.AddIndex(
            model_name='therapistavailability',
            index=models.Index(fields=['effective_from', 'effective_until'], name='avail_effective_idx'),
        ),
        migrations.AddField(
            model_name='therapistdateoverride',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='session',
            name='ai_key_topics',
        ),
        migrations.RemoveField(
            model_name='session',
            name='ai_mood_analysis',
        ),
        migrations.RemoveField(
            model_name='session',
            name='ai_recommendations',
        ),
        migrations.RemoveField(
            model_name='session',
            name='ai_sentiment_score',
        ),
        migrations.RemoveField(
            model_name='session',
            name='is_quick_session',
        ),
        migrations.RemoveField(
            model_name='session',
            name='quick_session_patient_name',
        ),
        migrations.RemoveField(
            model_name='session',
            name='transcription_id',
        ),
        migrations.RemoveField(
            model_name='therapistavailability',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='therapistavailability',
            name='max_sessions',
        ),
        migrations.RemoveField(
            model_name='therapistavailability',
            name='session_duration',
        ),
        migrations.AddIndex(
            model_name='therapistdateoverride',
            index=models.Index(fields=['therapist', 'date'], name='override_therapist_date_idx'),
        ),
        migrations.AddIndex(
            model_name='therapistdateoverride',
            index=models.Index(fields=['date', 'end_date'], name='override_date_range_idx'),
        ),
        migrations.AddConstraint(
            model_name='therapistdateoverride',
            constraint=models.UniqueConstraint(fields=('therapist', 'date'), name='unique_therapist_date_override'),
        ),
    ]
