# Generated by Django 5.2.3 on 2026-01-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0008_therapistdateoverride_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_summary',
            field=models.TextField(blank=True, help_text='Session summary for patient to view', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='summary_written_at',
            field=models.DateTimeField(blank=True, help_text='When therapist wrote the summary', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_notes',
            field=models.TextField(blank=True, help_text="Therapist's private session notes (not visible to patient)", null=True),
        ),
    ]
