# Generated by Django 5.2.3 on 2026-01-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_mood_individual_intensities'),
        ('therapy_sessions', '0009_add_session_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='goals_worked_on',
            field=models.ManyToManyField(blank=True, help_text='Therapy goals that were discussed/worked on in this session', related_name='sessions', to='patients.patientgoal'),
        ),
    ]
