# Generated by Django 5.2.3 on 2026-01-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0010_session_goals_worked_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='next_session_focus',
            field=models.TextField(blank=True, help_text='What will be focused on in the next session', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='recommendations',
            field=models.JSONField(blank=True, help_text='Array of recommendations/homework for patient (bullet points)', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_highlights',
            field=models.JSONField(blank=True, help_text='Array of key points/highlights from session (bullet points)', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_topics',
            field=models.JSONField(blank=True, help_text="Array of session topic tags e.g., ['Stress Management', 'Mindfulness', 'Family Dynamics']", null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='therapist_reflections',
            field=models.TextField(blank=True, help_text="Therapist's reflections/observations for patient (quoted text in italics)", null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='words_of_encouragement',
            field=models.TextField(blank=True, help_text='Encouraging message from therapist to patient', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='homework_assigned',
            field=models.TextField(blank=True, help_text='[DEPRECATED] Use recommendations instead', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='next_session_goals',
            field=models.TextField(blank=True, help_text='[DEPRECATED] Use next_session_focus instead', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='patient_goals',
            field=models.TextField(blank=True, help_text='[DEPRECATED] Use session_highlights instead', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_summary',
            field=models.TextField(blank=True, help_text='[DEPRECATED] Use structured fields instead', null=True),
        ),
    ]
