# Generated by Django 5.2.3 on 2026-01-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0011_session_next_session_focus_session_recommendations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='words_of_encouragement',
        ),
    ]
