# Generated by Django 5.2.3 on 2026-01-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0012_remove_session_words_of_encouragement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='session_highlights',
        ),
    ]
