# Generated by Django 5.2.3 on 2026-01-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0013_remove_session_session_highlights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='goals_worked_on',
        ),
        migrations.RemoveField(
            model_name='session',
            name='next_session_focus',
        ),
        migrations.RemoveField(
            model_name='session',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_topics',
        ),
        migrations.RemoveField(
            model_name='session',
            name='therapist_reflections',
        ),
        migrations.AlterField(
            model_name='session',
            name='homework_assigned',
            field=models.TextField(blank=True, help_text='Homework assigned to patient', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='next_session_goals',
            field=models.TextField(blank=True, help_text='Goals for next session', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='patient_goals',
            field=models.TextField(blank=True, help_text='Patient goals discussed in session', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_summary',
            field=models.TextField(blank=True, help_text='Summary of the session for patient', null=True),
        ),
    ]
