# Generated by Django 5.2.3 on 2025-08-04 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0018_alter_emailverificationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 19, 41, 57, 686925, tzinfo=datetime.timezone.utc)),
        ),
    ]
