# Generated by Django 5.2.3 on 2025-08-06 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0019_alter_emailverificationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 7, 17, 57, 13, 976138, tzinfo=datetime.timezone.utc)),
        ),
    ]
