# Generated by Django 5.2.3 on 2025-11-26 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0021_alter_emailverificationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 27, 12, 26, 44, 825055, tzinfo=datetime.timezone.utc)),
        ),
    ]
