# Generated by Django 5.2.3 on 2025-12-03 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0022_alter_emailverificationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 4, 6, 58, 15, 12132, tzinfo=datetime.timezone.utc)),
        ),
    ]
