# Generated by Django 5.2.3 on 2026-01-10 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0023_alter_emailverificationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 11, 8, 58, 29, 806383, tzinfo=datetime.timezone.utc)),
        ),
    ]
