# Generated by Django 5.2.3 on 2026-01-20 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0025_alter_emailverificationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 21, 13, 11, 0, 404503, tzinfo=datetime.timezone.utc)),
        ),
    ]
