# Generated by Django 5.2.3 on 2026-01-20 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0026_alter_emailverificationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 21, 14, 25, 22, 160409, tzinfo=datetime.timezone.utc)),
        ),
    ]
