# Generated by Django 5.2.3 on 2026-01-22 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0029_alter_emailverificationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 23, 14, 38, 42, 469918, tzinfo=datetime.timezone.utc)),
        ),
    ]
