# Generated by Django 5.2.3 on 2026-02-06 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0030_alter_emailverificationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 7, 14, 4, 40, 543186, tzinfo=datetime.timezone.utc)),
        ),
    ]
