# Generated by Django 5.2.3 on 2026-02-06 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0033_alter_emailverificationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 7, 18, 58, 41, 557926, tzinfo=datetime.timezone.utc)),
        ),
    ]
