# Generated by Django 5.2.3 on 2026-03-14 09:46

import authenticator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0034_alter_emailverificationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=authenticator.models.default_email_verification_expiry),
        ),
    ]
