# Generated by Django 5.2.3 on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0035_alter_emailverificationtoken_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
