# Generated by Django 5.2.3 on 2025-08-19 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOAPNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subjective', models.TextField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('assessment', models.TextField(blank=True, null=True)),
                ('plan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('reviewed', 'Reviewed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soap_notes', to=settings.AUTH_USER_MODEL)),
                ('sessions', models.ManyToManyField(related_name='soap_notes', to='sessions.session')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_soap_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'soap_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOAPTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('subjective_template', models.TextField(blank=True, null=True)),
                ('objective_template', models.TextField(blank=True, null=True)),
                ('assessment_template', models.TextField(blank=True, null=True)),
                ('plan_template', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soap_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'soap_templates',
            },
        ),
        migrations.CreateModel(
            name='SOAPNoteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('subjective', models.TextField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('assessment', models.TextField(blank=True, null=True)),
                ('plan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('soap_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='soap.soapnote')),
            ],
            options={
                'db_table': 'soap_note_versions',
                'unique_together': {('soap_note', 'version_number')},
            },
        ),
    ]
