# Generated by Django 5.2.3 on 2026-01-16 07:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInspiration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote', models.TextField(help_text='The inspirational quote')),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(choices=[('motivation', 'Motivation'), ('healing', 'Healing'), ('strength', 'Strength'), ('self_love', 'Self Love'), ('mindfulness', 'Mindfulness'), ('gratitude', 'Gratitude'), ('resilience', 'Resilience'), ('hope', 'Hope'), ('peace', 'Peace'), ('growth', 'Personal Growth')], max_length=20)),
                ('reflection_prompt', models.TextField(blank=True, help_text='Optional reflection question', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False, help_text='Featured quote of the day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Inspiration',
                'verbose_name_plural': 'Daily Inspirations',
                'db_table': 'daily_inspirations',
                'ordering': ['-featured', '?'],
                'indexes': [models.Index(fields=['is_active', 'featured'], name='daily_inspi_is_acti_db994f_idx'), models.Index(fields=['category'], name='daily_inspi_categor_c40824_idx')],
            },
        ),
        migrations.CreateModel(
            name='RelaxationContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content_type', models.CharField(choices=[('nature', 'Nature Sounds'), ('meditation', 'Guided Meditation'), ('breathing', 'Breathing Exercise'), ('music', 'Relaxing Music'), ('ambient', 'Ambient Sounds')], max_length=20)),
                ('category', models.CharField(choices=[('rain', 'Rain'), ('ocean', 'Ocean Waves'), ('forest', 'Forest'), ('birds', 'Birds'), ('wind', 'Wind'), ('fire', 'Crackling Fire'), ('meditation', 'Meditation'), ('sleep', 'Sleep'), ('focus', 'Focus'), ('anxiety', 'Anxiety Relief')], max_length=20)),
                ('audio_url', models.URLField(help_text='URL to audio file')),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(help_text='Duration in seconds')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('play_count', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Relaxation Content',
                'verbose_name_plural': 'Relaxation Content',
                'db_table': 'relaxation_content',
                'ordering': ['-play_count', 'title'],
                'indexes': [models.Index(fields=['content_type', 'category'], name='relaxation__content_183cd9_idx'), models.Index(fields=['is_active'], name='relaxation__is_acti_c97caa_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmotionalInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_emotion', models.CharField(choices=[('joy', 'Joy'), ('sadness', 'Sadness'), ('anger', 'Anger'), ('fear', 'Fear'), ('anxiety', 'Anxiety'), ('love', 'Love'), ('guilt', 'Guilt'), ('shame', 'Shame'), ('pride', 'Pride'), ('hope', 'Hope'), ('gratitude', 'Gratitude'), ('confusion', 'Confusion')], max_length=20)),
                ('intensity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('what_happened', models.TextField(help_text='What situation triggered this emotion?')),
                ('body_sensations', models.TextField(blank=True, help_text='Physical sensations experienced', null=True)),
                ('thoughts', models.TextField(blank=True, help_text='Thoughts during this emotion', null=True)),
                ('behaviors', models.TextField(blank=True, help_text='How did you respond/behave?', null=True)),
                ('insights_learned', models.TextField(blank=True, help_text='What did you learn from this?', null=True)),
                ('coping_strategies', models.TextField(blank=True, help_text='Strategies used to cope', null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('helpfulness_rating', models.IntegerField(blank=True, help_text='How helpful was this exploration? (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='emotional_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emotional Insight',
                'verbose_name_plural': 'Emotional Insights',
                'db_table': 'patient_emotional_insights',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', '-created_at'], name='patient_emo_patient_1dc2fa_idx'), models.Index(fields=['primary_emotion'], name='patient_emo_primary_b52d9f_idx'), models.Index(fields=['is_resolved'], name='patient_emo_is_reso_69511e_idx')],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, help_text='Text content of the journal', null=True)),
                ('entry_type', models.CharField(choices=[('text', 'Text Entry'), ('voice', 'Voice Recording'), ('mixed', 'Text & Voice')], default='text', max_length=10)),
                ('voice_recording_url', models.URLField(blank=True, help_text='URL to voice recording', null=True)),
                ('voice_duration_seconds', models.IntegerField(blank=True, help_text='Duration of voice recording', null=True)),
                ('voice_transcription', models.TextField(blank=True, help_text='Transcription of voice recording', null=True)),
                ('mood_tags', models.CharField(blank=True, help_text='Comma-separated mood tags', max_length=200, null=True)),
                ('is_private', models.BooleanField(default=True, help_text='If True, only patient can see. If False, therapist can also view')),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'db_table': 'patient_journal_entries',
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['patient', '-entry_date'], name='patient_jou_patient_b06ce4_idx'), models.Index(fields=['entry_date'], name='patient_jou_entry_d_66cc85_idx'), models.Index(fields=['is_favorite'], name='patient_jou_is_favo_fa85e5_idx'), models.Index(fields=['is_private'], name='patient_jou_is_priv_907b2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mood', models.CharField(choices=[('very_happy', 'Very Happy 😊'), ('happy', 'Happy 🙂'), ('neutral', 'Neutral 😐'), ('sad', 'Sad 😔'), ('very_sad', 'Very Sad 😢'), ('anxious', 'Anxious 😰'), ('angry', 'Angry 😠'), ('stressed', 'Stressed 😣'), ('calm', 'Calm 😌'), ('excited', 'Excited 🤩')], max_length=20)),
                ('intensity', models.IntegerField(help_text='Mood intensity from 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the mood', null=True)),
                ('triggers', models.TextField(blank=True, help_text='What triggered this mood?', null=True)),
                ('activities', models.TextField(blank=True, help_text='Activities during this mood', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mood_date', models.DateField(default=django.utils.timezone.now, help_text='Date of the mood entry')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mood Entry',
                'verbose_name_plural': 'Mood Entries',
                'db_table': 'patient_mood_entries',
                'ordering': ['-mood_date', '-created_at'],
                'indexes': [models.Index(fields=['patient', '-mood_date'], name='patient_moo_patient_3f1aca_idx'), models.Index(fields=['mood_date'], name='patient_moo_mood_da_563f68_idx'), models.Index(fields=['mood'], name='patient_moo_mood_648261_idx')],
                'unique_together': {('patient', 'mood_date')},
            },
        ),
        migrations.CreateModel(
            name='PatientGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='not_started', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('milestones', models.TextField(blank=True, help_text='JSON or comma-separated milestones', null=True)),
                ('created_by_therapist', models.BooleanField(default=False, help_text='True if therapist created this goal')),
                ('therapist_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='therapy_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Goal',
                'verbose_name_plural': 'Patient Goals',
                'db_table': 'patients_goals',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='patients_go_patient_4e650a_idx'), models.Index(fields=['status'], name='patients_go_status_234d75_idx'), models.Index(fields=['target_date'], name='patients_go_target__fef856_idx')],
            },
        ),
        migrations.CreateModel(
            name='RelaxationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_listened_seconds', models.IntegerField(help_text='How long patient listened')),
                ('completed', models.BooleanField(default=False, help_text='Did patient complete the full content?')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('mood_before', models.CharField(blank=True, help_text='Mood before session', max_length=20, null=True)),
                ('mood_after', models.CharField(blank=True, help_text='Mood after session', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='patients.relaxationcontent')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='relaxation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relaxation Session',
                'verbose_name_plural': 'Relaxation Sessions',
                'db_table': 'relaxation_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['patient', '-started_at'], name='relaxation__patient_fb46f6_idx'), models.Index(fields=['content'], name='relaxation__content_cf6ad4_idx')],
            },
        ),
    ]
