# Generated by Django 5.2.3 on 2026-01-16 07:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelaxationTip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('tip_type', models.CharField(choices=[('breathing', 'Breathing Technique'), ('visualization', 'Visualization'), ('position', 'Comfortable Position'), ('distraction', 'Minimize Distractions'), ('general', 'General Tip')], max_length=20)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji for the tip', max_length=50, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Relaxation Tip',
                'verbose_name_plural': 'Relaxation Tips',
                'db_table': 'relaxation_tips',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='relaxationcontent',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions for guided meditations', null=True),
        ),
    ]
