# Generated by Django 5.2.3 on 2026-01-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_relaxationtip_relaxationcontent_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relaxationcontent',
            name='category',
            field=models.CharField(choices=[('rain', 'Rain'), ('ocean', 'Ocean'), ('forest', 'Forest'), ('birds', 'Birds'), ('wind', 'Wind'), ('fire', 'Fire'), ('nature', 'Nature'), ('ambient', 'Ambient'), ('meditation', 'Meditation'), ('breathing', 'Breathing'), ('visualization', 'Visualization'), ('sleep', 'Sleep'), ('focus', 'Focus'), ('anxiety', 'Anxiety Relief')], max_length=20),
        ),
        migrations.AlterField(
            model_name='relaxationcontent',
            name='content_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('guided_meditation', 'Guided Meditation'), ('nature', 'Nature Sounds'), ('meditation', 'Meditation'), ('breathing', 'Breathing Exercise'), ('music', 'Relaxing Music'), ('ambient', 'Ambient Sounds')], max_length=20),
        ),
    ]
