# Generated by Django 5.2.3 on 2026-01-16 09:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_update_relaxation_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='prompt',
            field=models.TextField(blank=True, help_text='Daily prompt that inspired this entry', null=True),
        ),
        migrations.CreateModel(
            name='JournalPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(help_text='Journal prompt question')),
                ('category', models.CharField(choices=[('feelings', 'Feelings'), ('gratitude', 'Gratitude'), ('reflection', 'Reflection'), ('goals', 'Goals'), ('mindfulness', 'Mindfulness'), ('relationships', 'Relationships'), ('growth', 'Personal Growth'), ('challenges', 'Challenges'), ('creativity', 'Creativity'), ('self_care', 'Self Care')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description or guidance', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal Prompt',
                'verbose_name_plural': 'Journal Prompts',
                'db_table': 'journal_prompts',
                'ordering': ['?'],
                'indexes': [models.Index(fields=['is_active'], name='journal_pro_is_acti_661ef3_idx'), models.Index(fields=['category'], name='journal_pro_categor_9bfe7d_idx')],
            },
        ),
    ]
