# Generated by Django 5.2.3 on 2026-01-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_journal_enhancements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='entry_type',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='voice_duration_seconds',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='voice_recording_url',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='voice_transcription',
        ),
    ]
