# Generated by Django 5.2.3 on 2026-01-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_voice_recording'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='moodentry',
            name='patient_moo_mood_648261_idx',
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='mood',
        ),
        migrations.AddField(
            model_name='moodentry',
            name='moods',
            field=models.CharField(default='happy', help_text="Comma-separated mood values (e.g., 'happy,grateful,peaceful')", max_length=200),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='intensity',
            field=models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], default=3, help_text='Mood intensity from 1 (Very Low) to 5 (Very High)'),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='triggers',
            field=models.CharField(blank=True, help_text="Comma-separated trigger categories (e.g., 'work,sleep,health')", max_length=200, null=True),
        ),
    ]
