# Generated by Django 5.2.3 on 2026-01-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_update_mood_tracker'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moodentry',
            unique_together=set(),
        ),
    ]
