# Generated by Django 5.2.3 on 2026-01-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_allow_multiple_entries_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodentry',
            name='intensity',
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='moods',
        ),
        migrations.AddField(
            model_name='moodentry',
            name='mood_intensities',
            field=models.JSONField(default=dict, help_text="Dictionary of moods with their intensity levels (1-5). Example: {'happy': 4, 'grateful': 5}"),
        ),
    ]
