# Generated by Django 5.2.3 on 2026-01-20 13:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_mood_individual_intensities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_reminders_enabled', models.BooleanField(default=True, help_text='Receive reminders for upcoming sessions')),
                ('session_reminder_time', models.IntegerField(default=24, help_text='Hours before session to send reminder (default: 24 hours)')),
                ('session_summary_enabled', models.BooleanField(default=True, help_text='Receive notification when therapist writes session summary')),
                ('session_approved_enabled', models.BooleanField(default=True, help_text='Receive notification when session request is approved')),
                ('session_cancelled_enabled', models.BooleanField(default=True, help_text='Receive notification when session is cancelled')),
                ('goal_reminders_enabled', models.BooleanField(default=True, help_text='Receive reminders for therapy goals')),
                ('mood_reminder_enabled', models.BooleanField(default=True, help_text='Daily reminder to log mood')),
                ('mood_reminder_time', models.TimeField(default='20:00:00', help_text='Time of day to send mood reminder')),
                ('journal_reminder_enabled', models.BooleanField(default=True, help_text='Daily reminder to write journal entry')),
                ('journal_reminder_time', models.TimeField(default='21:00:00', help_text='Time of day to send journal reminder')),
                ('therapist_messages_enabled', models.BooleanField(default=True, help_text='Receive notifications from therapist')),
                ('push_token', models.CharField(blank=True, help_text='FCM/APNS push notification token', max_length=500, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('session_reminder', 'Session Reminder'), ('session_summary', 'Session Summary Available'), ('session_approved', 'Session Request Approved'), ('session_cancelled', 'Session Cancelled'), ('goal_reminder', 'Goal Reminder'), ('mood_reminder', 'Mood Check-in Reminder'), ('journal_reminder', 'Journal Reminder'), ('therapist_message', 'Message from Therapist'), ('general', 'General Notification')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('session_id', models.UUIDField(blank=True, help_text='Related session ID', null=True)),
                ('goal_id', models.UUIDField(blank=True, help_text='Related goal ID', null=True)),
                ('action_url', models.CharField(blank=True, help_text='Deep link to open in mobile app', max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('push_sent', models.BooleanField(default=False)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('push_error', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['patient', '-sent_at'], name='notificatio_patient_56d0da_idx'), models.Index(fields=['patient', 'is_read'], name='notificatio_patient_491686_idx')],
            },
        ),
    ]
