# Generated by Django 5.2.3 on 2026-01-25 11:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_notificationpreference_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('exercise', 'Exercise/Physical Activity'), ('meditation', 'Meditation/Mindfulness'), ('social', 'Social Activity'), ('work', 'Work/Study'), ('hobby', 'Hobby/Creative Activity'), ('therapy', 'Therapy Session'), ('rest', 'Rest/Relaxation'), ('outdoor', 'Outdoor Activity'), ('creative', 'Creative Activity'), ('music', 'Music'), ('reading', 'Reading'), ('cooking', 'Cooking'), ('study', 'Study/Learning'), ('other', 'Other')], max_length=20)),
                ('activity_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('intensity', models.IntegerField(blank=True, help_text='Activity intensity (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('mood_before', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('mood_after', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('energy_before', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('energy_after', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('with_others', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('activity_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'patient_activity_logs',
                'ordering': ['-activity_date'],
            },
        ),
    ]
