# Generated by Django 5.2.3 on 2026-03-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_notification_delivery_lifecycle'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_deliver_4d5d19_idx',
            old_name='notificatio_deliver_a6a03e_idx',
        ),
    ]
