# Generated by Django 5.2.3 on 2026-04-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_notificationdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('session_reminder', 'Session Reminder'), ('session_summary', 'Session Summary Available'), ('session_ai_ready', 'Session AI Outputs Ready'), ('session_approved', 'Session Request Approved'), ('session_cancelled', 'Session Cancelled'), ('goal_reminder', 'Goal Reminder'), ('mood_reminder', 'Mood Check-in Reminder'), ('journal_reminder', 'Journal Reminder'), ('therapist_message', 'Message from Therapist'), ('general', 'General Notification')], max_length=50),
        ),
    ]
